import type { MetadataRoute } from "next"

/**
 * Served by Next.js at /manifest.webmanifest, linked from app/layout.tsx.
 *
 * The icon list is generated by scripts/generate-pwa-icons.mjs — regenerate it
 * rather than hand-editing entries here, because the `any` and `maskable` art
 * differ on purpose (maskable is inset to survive Android's adaptive-icon crop)
 * and the declared `sizes` have to match the real bitmaps to stay installable.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    // Pins the app's identity independently of start_url. Without it a later
    // change to start_url reads as a different app and installed users are
    // stranded on the old one.
    id: "/",
    name: "UP — opportunities, events, and resources",
    short_name: "UP",
    description: "Connect young ambitious people to opportunities, events, and free resources.",
    start_url: "/",
    display: "standalone",
    display_override: ["standalone", "minimal-ui"],
    background_color: "#0B1222",
    theme_color: "#ff6700",
    orientation: "portrait-primary",
    scope: "/",
    lang: "en",
    dir: "ltr",
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icons/icon-maskable-192.png", sizes: "192x192", type: "image/png", purpose: "maskable" },
      { src: "/icons/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
    // Long-press the installed icon. Kept to four, which is all Android surfaces.
    shortcuts: [
      { name: "Search", short_name: "Search", url: "/search", icons: [{ src: "/icons/icon-192.png", sizes: "192x192" }] },
      { name: "Opportunities", short_name: "Opportunities", url: "/opportunities", icons: [{ src: "/icons/icon-192.png", sizes: "192x192" }] },
      { name: "Events", short_name: "Events", url: "/events", icons: [{ src: "/icons/icon-192.png", sizes: "192x192" }] },
      { name: "Jobs", short_name: "Jobs", url: "/jobs", icons: [{ src: "/icons/icon-192.png", sizes: "192x192" }] },
    ],
    categories: ["social", "lifestyle", "education"],
    prefer_related_applications: false,
  }
}
